### ISSUE TITLE
Broken with several plugin_dir

### ISSUE THREAD

**Issue by fridobox** [fredericd/Koha-Plugin-Tamil-Mirabel#2]
Koha now allows several plugin_dir.
In this cas your code can not use :+1: 
[% INCLUDE "$PLUGIN_DIR/head.tt" %]

https://github.com/fredericd/Koha-Plugin-Tamil-Mirabel/blob/26e9395f05e0c3c15c24f2f6e921c394d0fe4348/Koha/Plugin/Tamil/Mirabel/home.tt#L1

Maybe use Koha::Plugin->bundle_path()

**Comment by fredericd** [comment]
Thanks for this. I propose a fix Koha side, with bug 26803.

**Comment by Liliputech** [comment]
Got things to work while applying bz 26803 on Koha :) thx!

**Comment by fridobox** [comment]
Ok super, its on tracks :
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=26803
