### ISSUE TITLE
missing file in source

### ISSUE THREAD

**Issue by Liliputech** [fredericd/Koha-Plugin-Tamil-Mirabel#3]
While trying with BZ26803 I got this error when trying to reach page "Mes accès" :
`Template process failed: file error - /var/lib/koha/kohadev/plugins/Koha/Plugin/Tamil/Mirabel/invalidid.tt: not found at /kohadevbox/koha/C4/Templates.pm line 122`

**Comment by fredericd** [comment]
Which versions do you use? Koha and plugin?

**Comment by Liliputech** [comment]
I used koha and plugin master, from sources

**Comment by fredericd** [comment]
What do you have in /var/lib/koha/kohadev/plugins/Koha/Plugin/Tamil/Mirabel directory? Don't you have all TT templates? home.tt, head.tt, invalidid.tt, etc.

**Comment by Liliputech** [comment]
It's missing "invalidid.tt" (missing on the repository, maybe just forgot a git add on this file...?)

**Comment by fredericd** [comment]
Yes, that's it. It is in the .kpz file, but not in the repo. Will be there in minute!
